//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.ClaimsBasicMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccorOTADBEntities : DbContext
    {
        public AccorOTADBEntities()
            : base("name=AccorOTADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANPOL_Extract> CANPOL_Extract { get; set; }
        public virtual DbSet<ModelPushLog> ModelPushLog { get; set; }
        public virtual DbSet<OTA_HotelInfoHZToAccor> OTA_HotelInfoHZToAccor { get; set; }
        public virtual DbSet<OTA_RoomPriceDataCache> OTA_RoomPriceDataCache { get; set; }
        public virtual DbSet<OTAAccorPushCountData> OTAAccorPushCountData { get; set; }
        public virtual DbSet<OTAAccorPushDataXmlResult> OTAAccorPushDataXmlResult { get; set; }
        public virtual DbSet<OTAAccorPushPriceData> OTAAccorPushPriceData { get; set; }
        public virtual DbSet<OTAAccorPushSalesBookingRuleData> OTAAccorPushSalesBookingRuleData { get; set; }
        public virtual DbSet<PushLog> PushLog { get; set; }
        public virtual DbSet<AccorDataPushHistory> AccorDataPushHistory { get; set; }
        public virtual DbSet<OTA_HOD_Info> OTA_HOD_Info { get; set; }
        public virtual DbSet<OTA_HOD_RoomCode_Info> OTA_HOD_RoomCode_Info { get; set; }
        public virtual DbSet<OTAAccorPushSalesAvailData> OTAAccorPushSalesAvailData { get; set; }
        public virtual DbSet<OTAPushRedisResultInfo> OTAPushRedisResultInfo { get; set; }
        public virtual DbSet<RoomCountDataCache> RoomCountDataCache { get; set; }
    }
}
