//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Ioc.ClaimsBasicMvc.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OTA_RoomPriceDataCache
    {
        public int ID { get; set; }
        public string HotelID { get; set; }
        public string RoomType { get; set; }
        public decimal HotelPrice { get; set; }
        public decimal MarketPrice { get; set; }
        public string PriceCheck { get; set; }
        [JsonConverter(typeof(IsoDateTimeConverter))]
        public System.DateTime BizDate { get; set; }
        public bool HashPush { get; set; }
        [JsonConverter(typeof(IsoDateTimeConverter))]
        public System.DateTime LastModifyDate { get; set; }
        [JsonConverter(typeof(IsoDateTimeConverter))]
        public System.DateTime CreateDate { get; set; }
        public bool IsDel { get; set; }
    }
}
