//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.AutofacWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANPOL_Extract
    {
        public int ID { get; set; }
        public string HotelID { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Mon { get; set; }
        public string Tue { get; set; }
        public string Wed { get; set; }
        public string Thu { get; set; }
        public string Fri { get; set; }
        public string Sat { get; set; }
        public string Sun { get; set; }
        public string Display { get; set; }
        public string Nb_brackets { get; set; }
        public string Forbidden { get; set; }
        public string FromDays { get; set; }
        public string ToDays { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Penalty_status { get; set; }
        public string Amount { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
