//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.AutofacWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTA_HOD_Info
    {
        public string HotelCode { get; set; }
        public string HotelName { get; set; }
        public string LastModifiedTime { get; set; }
        public string BrandCode { get; set; }
        public string BrandName { get; set; }
        public string hotelStatus { get; set; }
    }
}
