//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.AutofacWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTAPushRedisResultInfo
    {
        public string HotelId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string PushType { get; set; }
        public string Content { get; set; }
        public string BackResult { get; set; }
        public Nullable<decimal> WorkTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
