//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.AutofacWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCountDataCache
    {
        public long ID { get; set; }
        public string CheckInDate { get; set; }
        public string HotelId { get; set; }
        public bool HasRoom { get; set; }
        public string RoomTypeCode { get; set; }
        public bool HashPush { get; set; }
        public System.DateTime LastModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDel { get; set; }
        public int SourceType { get; set; }
    }
}
