//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.AutofacWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CheckHotelInfo
    {
        public long Id { get; set; }
        public string HotelCode { get; set; }
        public string RoomCode { get; set; }
        public int MaxOccupancy { get; set; }
        public string HotelID { get; set; }
        public string RatePlanCode { get; set; }
        public string RoomTypeCode { get; set; }
    }
}
