//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpringNetWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelView", Namespace="http://schemas.datacontract.org/2004/07/HZ.CentralGateway.Entity.Common.View1")]
    [System.SerializableAttribute()]
    public partial class HotelView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpringNetWCF.ServiceReference1.HotelRoomTypeEx[] HotelRoomTypeExField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpringNetWCF.ServiceReference1.HotelRoomTypeEx[] HotelRoomTypeEx {
            get {
                return this.HotelRoomTypeExField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelRoomTypeExField, value) != true)) {
                    this.HotelRoomTypeExField = value;
                    this.RaisePropertyChanged("HotelRoomTypeEx");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelRoomTypeEx", Namespace="http://schemas.datacontract.org/2004/07/HZ.CentralGateway.Entity.Common")]
    [System.SerializableAttribute()]
    public partial class HotelRoomTypeEx : SpringNetWCF.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADSLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedTypeShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasSomkeFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsADSLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsADSLWifiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsHasWindowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaxCheckInPeoNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADSL {
            get {
                return this.ADSLField;
            }
            set {
                if ((object.ReferenceEquals(this.ADSLField, value) != true)) {
                    this.ADSLField = value;
                    this.RaisePropertyChanged("ADSL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BedType {
            get {
                return this.BedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BedTypeField, value) != true)) {
                    this.BedTypeField = value;
                    this.RaisePropertyChanged("BedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BedTypeShort {
            get {
                return this.BedTypeShortField;
            }
            set {
                if ((object.ReferenceEquals(this.BedTypeShortField, value) != true)) {
                    this.BedTypeShortField = value;
                    this.RaisePropertyChanged("BedTypeShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BedWidth {
            get {
                return this.BedWidthField;
            }
            set {
                if ((object.ReferenceEquals(this.BedWidthField, value) != true)) {
                    this.BedWidthField = value;
                    this.RaisePropertyChanged("BedWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorPlace {
            get {
                return this.FloorPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorPlaceField, value) != true)) {
                    this.FloorPlaceField = value;
                    this.RaisePropertyChanged("FloorPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasSomkeFree {
            get {
                return this.HasSomkeFreeField;
            }
            set {
                if ((object.ReferenceEquals(this.HasSomkeFreeField, value) != true)) {
                    this.HasSomkeFreeField = value;
                    this.RaisePropertyChanged("HasSomkeFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelArea {
            get {
                return this.HotelAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAreaField, value) != true)) {
                    this.HotelAreaField = value;
                    this.RaisePropertyChanged("HotelArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsADSL {
            get {
                return this.IsADSLField;
            }
            set {
                if ((object.ReferenceEquals(this.IsADSLField, value) != true)) {
                    this.IsADSLField = value;
                    this.RaisePropertyChanged("IsADSL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsADSLWifi {
            get {
                return this.IsADSLWifiField;
            }
            set {
                if ((object.ReferenceEquals(this.IsADSLWifiField, value) != true)) {
                    this.IsADSLWifiField = value;
                    this.RaisePropertyChanged("IsADSLWifi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsHasWindow {
            get {
                return this.IsHasWindowField;
            }
            set {
                if ((object.ReferenceEquals(this.IsHasWindowField, value) != true)) {
                    this.IsHasWindowField = value;
                    this.RaisePropertyChanged("IsHasWindow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxCheckInPeoNum {
            get {
                return this.MaxCheckInPeoNumField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxCheckInPeoNumField, value) != true)) {
                    this.MaxCheckInPeoNumField = value;
                    this.RaisePropertyChanged("MaxCheckInPeoNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomNum {
            get {
                return this.RoomNumField;
            }
            set {
                if ((this.RoomNumField.Equals(value) != true)) {
                    this.RoomNumField = value;
                    this.RaisePropertyChanged("RoomNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomTypeID {
            get {
                return this.RoomTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeIDField, value) != true)) {
                    this.RoomTypeIDField = value;
                    this.RaisePropertyChanged("RoomTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/HZ.ReservationGateway.Common.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpringNetWCF.ServiceReference1.HotelRoomTypeEx))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreateTimek__BackingFieldField;
        
        private bool IsDeletedk__BackingFieldField;
        
        private System.DateTime ModifyTimek__BackingFieldField;
        
        private byte[] Timestampk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateTime>k__BackingField", IsRequired=true)]
        public System.DateTime CreateTimek__BackingField {
            get {
                return this.CreateTimek__BackingFieldField;
            }
            set {
                if ((this.CreateTimek__BackingFieldField.Equals(value) != true)) {
                    this.CreateTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsDeleted>k__BackingField", IsRequired=true)]
        public bool IsDeletedk__BackingField {
            get {
                return this.IsDeletedk__BackingFieldField;
            }
            set {
                if ((this.IsDeletedk__BackingFieldField.Equals(value) != true)) {
                    this.IsDeletedk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsDeletedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModifyTime>k__BackingField", IsRequired=true)]
        public System.DateTime ModifyTimek__BackingField {
            get {
                return this.ModifyTimek__BackingFieldField;
            }
            set {
                if ((this.ModifyTimek__BackingFieldField.Equals(value) != true)) {
                    this.ModifyTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("ModifyTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Timestamp>k__BackingField", IsRequired=true)]
        public byte[] Timestampk__BackingField {
            get {
                return this.Timestampk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Timestampk__BackingFieldField, value) != true)) {
                    this.Timestampk__BackingFieldField = value;
                    this.RaisePropertyChanged("Timestampk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelInfo", ReplyAction="http://tempuri.org/IHotelService/GetHotelInfoResponse")]
        SpringNetWCF.ServiceReference1.HotelView GetHotelInfo(string hotelId, string roomType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotelInfo", ReplyAction="http://tempuri.org/IHotelService/GetHotelInfoResponse")]
        System.Threading.Tasks.Task<SpringNetWCF.ServiceReference1.HotelView> GetHotelInfoAsync(string hotelId, string roomType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : SpringNetWCF.ServiceReference1.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<SpringNetWCF.ServiceReference1.IHotelService>, SpringNetWCF.ServiceReference1.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpringNetWCF.ServiceReference1.HotelView GetHotelInfo(string hotelId, string roomType) {
            return base.Channel.GetHotelInfo(hotelId, roomType);
        }
        
        public System.Threading.Tasks.Task<SpringNetWCF.ServiceReference1.HotelView> GetHotelInfoAsync(string hotelId, string roomType) {
            return base.Channel.GetHotelInfoAsync(hotelId, roomType);
        }
    }
}
