//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.Spring.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccorDataPushHistory
    {
        public string HotelCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string InvTypeCode { get; set; }
        public string RatePlanCode { get; set; }
        public string LocatorID { get; set; }
        public System.DateTime PushTime { get; set; }
        public System.DateTime SaveTime { get; set; }
        public string ContextJson { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public string PushType { get; set; }
    }
}
