//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioc.Spring.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTAAccorPushSalesBookingRuleData
    {
        public long D { get; set; }
        public string TimeStamp { get; set; }
        public string EchoToken { get; set; }
        public string Target { get; set; }
        public string Version { get; set; }
        public string PrimaryLangID { get; set; }
        public string HotelCode { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<bool> IsRoom { get; set; }
        public string InvTypeCode { get; set; }
        public string RatePlanCode { get; set; }
        public string BrandCode { get; set; }
        public string ChainCode { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Weds { get; set; }
        public Nullable<bool> Thur { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
